-- HISTORICAL BOOTSTRAP -- the family Google Sheet is now the source of truth.
--
-- The passport-sync edge function replaces every country and state row for
-- anyone who has a column in the sheet, so running this file against a
-- database that has already synced changes nothing you will see. It is kept
-- for provenance and to seed a brand-new database before the first sync.
--
-- Note the country codes below predate splitting the United Kingdom into
-- England / Scotland / Wales / Northern Ireland; the first sync corrects them.
--
-- Safe to re-run. Requires migrations 00005 and 00006 first.

-- 1. Family members (only inserted if not already present by name)
insert into public.family_members (name, sort_index)
select v.name, v.idx from (values
  ('John', 1),
  ('Nancy', 2),
  ('Kathryn', 3),
  ('Sahil', 4),
  ('Will', 5),
  ('Rickie', 6)
) as v(name, idx)
where not exists (select 1 from public.family_members fm where fm.name = v.name);

-- 2. Countries visited
insert into public.country_visits (member_id, country_code)
select fm.id, v.code from (values
  ('John', 'GB'),
  ('John', 'IE'),
  ('John', 'FR'),
  ('John', 'ES'),
  ('John', 'PT'),
  ('John', 'IT'),
  ('John', 'NL'),
  ('John', 'DE'),
  ('John', 'DK'),
  ('John', 'NO'),
  ('John', 'GR'),
  ('John', 'HU'),
  ('John', 'TR'),
  ('John', 'RU'),
  ('John', 'CA'),
  ('John', 'MX'),
  ('John', 'CU'),
  ('John', 'BR'),
  ('John', 'CL'),
  ('John', 'AR'),
  ('John', 'BH'),
  ('John', 'SA'),
  ('John', 'QA'),
  ('John', 'KW'),
  ('John', 'OM'),
  ('John', 'JO'),
  ('John', 'IN'),
  ('John', 'TH'),
  ('John', 'SG'),
  ('John', 'KH'),
  ('John', 'AU'),
  ('John', 'ZA'),
  ('John', 'EG'),
  ('John', 'BB'),
  ('Nancy', 'GB'),
  ('Nancy', 'IE'),
  ('Nancy', 'FR'),
  ('Nancy', 'PT'),
  ('Nancy', 'NL'),
  ('Nancy', 'DE'),
  ('Nancy', 'IT'),
  ('Nancy', 'NO'),
  ('Nancy', 'GR'),
  ('Nancy', 'HU'),
  ('Nancy', 'CZ'),
  ('Nancy', 'CA'),
  ('Nancy', 'MX'),
  ('Nancy', 'TH'),
  ('Nancy', 'BB'),
  ('Kathryn', 'GB'),
  ('Kathryn', 'CH'),
  ('Kathryn', 'DE'),
  ('Kathryn', 'CZ'),
  ('Kathryn', 'IT'),
  ('Kathryn', 'CR'),
  ('Kathryn', 'HN'),
  ('Kathryn', 'BZ'),
  ('Kathryn', 'CA'),
  ('Kathryn', 'TH'),
  ('Kathryn', 'SG'),
  ('Kathryn', 'ID'),
  ('Kathryn', 'BB'),
  ('Sahil', 'TH'),
  ('Sahil', 'SG'),
  ('Sahil', 'ID'),
  ('WR', 'GB'),
  ('WR', 'IE'),
  ('WR', 'FR'),
  ('WR', 'ES'),
  ('WR', 'IT'),
  ('WR', 'CH'),
  ('WR', 'AT'),
  ('WR', 'DE'),
  ('WR', 'DK'),
  ('WR', 'GR'),
  ('WR', 'CZ'),
  ('WR', 'IS'),
  ('WR', 'TR'),
  ('WR', 'MX'),
  ('WR', 'BR'),
  ('WR', 'EC'),
  ('WR', 'VN'),
  ('WR', 'TH'),
  ('WR', 'MM'),
  ('WR', 'KE'),
  ('WR', 'TZ'),
  ('WR', 'RW'),
  ('WR', 'CD'),
  ('WR', 'BB'),
  ('Rickie', 'FR'),
  ('Rickie', 'ES'),
  ('Rickie', 'CH'),
  ('Rickie', 'AT'),
  ('Rickie', 'GR'),
  ('Rickie', 'DK'),
  ('Rickie', 'GB'),
  ('Rickie', 'KE'),
  ('Rickie', 'TZ')
) as v(name, code)
join public.family_members fm on fm.name = v.name
on conflict (member_id, country_code) do nothing;

-- 3. US states visited
insert into public.state_visits (member_id, state_code)
select fm.id, v.code from (values
  ('WR', 'TX'),
  ('WR', 'GA'),
  ('WR', 'NC'),
  ('WR', 'SC'),
  ('WR', 'LA'),
  ('WR', 'MS'),
  ('WR', 'AL'),
  ('WR', 'FL'),
  ('WR', 'CO'),
  ('WR', 'VA'),
  ('WR', 'MD'),
  ('WR', 'UT'),
  ('WR', 'WY'),
  ('WR', 'AR'),
  ('WR', 'PA'),
  ('WR', 'WV'),
  ('WR', 'DE'),
  ('WR', 'NV'),
  ('WR', 'AZ'),
  ('WR', 'NM'),
  ('WR', 'MA'),
  ('WR', 'NH'),
  ('WR', 'MT'),
  ('WR', 'TN'),
  ('WR', 'KY'),
  ('WR', 'IN'),
  ('WR', 'IL'),
  ('WR', 'CA'),
  ('WR', 'HI'),
  ('WR', 'NJ'),
  ('WR', 'NY'),
  ('WR', 'CT'),
  ('WR', 'WA'),
  ('WR', 'MI'),
  ('WR', 'WI'),
  ('WR', 'ND'),
  ('WR', 'ID'),
  ('WR', 'OR'),
  ('WR', 'AK'),
  ('WR', 'IA'),
  ('WR', 'KS'),
  ('WR', 'ME'),
  ('WR', 'MO'),
  ('WR', 'NE'),
  ('WR', 'OH'),
  ('WR', 'OK'),
  ('WR', 'RI'),
  ('WR', 'SD'),
  ('WR', 'VT'),
  ('Kathryn', 'TX'),
  ('Kathryn', 'LA'),
  ('Kathryn', 'MS'),
  ('Kathryn', 'AL'),
  ('Kathryn', 'FL'),
  ('Kathryn', 'CO'),
  ('Kathryn', 'GA'),
  ('Kathryn', 'VA'),
  ('Kathryn', 'MD'),
  ('Kathryn', 'UT'),
  ('Kathryn', 'WY'),
  ('Kathryn', 'AR'),
  ('Kathryn', 'WV'),
  ('Kathryn', 'PA'),
  ('Kathryn', 'DE'),
  ('Kathryn', 'NV'),
  ('Kathryn', 'AZ'),
  ('Kathryn', 'NM'),
  ('Kathryn', 'MA'),
  ('Kathryn', 'NH'),
  ('Kathryn', 'SC'),
  ('Kathryn', 'NC'),
  ('Kathryn', 'TN'),
  ('Kathryn', 'MT'),
  ('Kathryn', 'KY'),
  ('Kathryn', 'IN'),
  ('Kathryn', 'IL'),
  ('Kathryn', 'CA'),
  ('Kathryn', 'HI'),
  ('Kathryn', 'NJ'),
  ('Kathryn', 'NY'),
  ('Kathryn', 'CT'),
  ('Kathryn', 'WA'),
  ('Kathryn', 'RI'),
  ('Kathryn', 'OH'),
  ('Kathryn', 'MO'),
  ('Kathryn', 'KS'),
  ('Kathryn', 'IA'),
  ('Kathryn', 'ID'),
  ('Kathryn', 'OR'),
  ('Kathryn', 'AK'),
  ('Kathryn', 'ME'),
  ('Kathryn', 'MI'),
  ('Kathryn', 'NE'),
  ('Kathryn', 'ND'),
  ('Kathryn', 'OK'),
  ('Kathryn', 'SD'),
  ('Kathryn', 'VT'),
  ('Kathryn', 'WI')
) as v(name, code)
join public.family_members fm on fm.name = v.name
on conflict (member_id, state_code) do nothing;


